#!/bin/bash

timeout --foreground -s STOP -k 5s $2 mplayer -dumpstream -dumpfile /tv/movies/$3.ts dvb://$1 >> /tv/logs/`date -I`_$3_record 2>&1

sleep 1m

ffmpeg -y -i /tv/movies/$3.ts -vcodec h264 -acodec aac -strict -2 /tv/movies/`date -I`_$3.mp4 >> /tv/logs/`date -I`_$3_ffmpeg 2>&1
